### PR TITLE
Rain Code US 1.3.2 60fps update

### PR DESCRIPTION
**Pull request by DuIslingr**

### CODE REVIEW

**Comment by StevensND** [comment]
Tysm for the updated code!. 

I didn't know there was an update for the game. I have not had access to it yet. As soon as I have it I will update the rest :)

**Comment by DuIslingr** [comment]
Np it came out on Friday.  I can say the res mods seem to be unaffected but ive only used the 1440p one.

**Comment by StevensND** [comment]
> Np it came out on Friday. I can say the res mods seem to be unaffected but ive only used the 1440p one.

They're romfs. Except they modify game files it's not necessary to update them.

**Comment by StevensND** [comment]
Finally I got 1.3.2 EU Version. Ty again :)

**Comment by StevensND** [comment]
1.3.3 Version has been released. Let me know if you've the update and can update the code :)

**Pull request merged**
